import os
import argparse
import h5py
import numpy as np
import matplotlib.pyplot as plt
import trimesh

def visualize_depth(depth_map, frame_idx):
    """Visualizes the 2D Metric Depth Map using matplotlib."""
    if depth_map is None or depth_map.size == 0:
        print("Depth map is empty.")
        return

    plt.figure(figsize=(8, 6))
    # We display it as an image heatmap.
    img = plt.imshow(depth_map, cmap='viridis')
    plt.colorbar(img, label="Depth (Metric Scale)")
    plt.title(f"MoGe-2 Depth Map - Frame {frame_idx}")
    plt.tight_layout()
    plt.show()

def visualize_mesh(vertices, use_surface=False, faces=None):
    """Visualizes the 3D Hand Mesh as a Point Cloud or Surface."""
    if vertices is None or vertices.size == 0:
        print("Mesh vertices array is empty.")
        return
        
    print(f"Visualizing vertices format: {vertices.shape}")

    scene = trimesh.Scene()
    
    if use_surface and faces is not None:
        # Render as a fully connected surface mesh if MANO faces are provided
        mesh = trimesh.Trimesh(vertices=vertices, faces=faces)
        mesh.visual.vertex_colors = [255, 150, 150, 255] # Skin-like base color
        scene.add_geometry(mesh)
    elif use_surface and faces is None:
        print("WARNING: 'surface' was requested but MANO faces were not provided/found.")
        print("Falling back to rendering computing a Convex Hull overlaying a Point Cloud.")
        
        point_cloud = trimesh.points.PointCloud(vertices)
        
        try:
            hull = point_cloud.convex_hull
            # Transparent Green
            hull.visual.vertex_colors = [150, 255, 150, 150] 
            scene.add_geometry(hull)
        except Exception as e:
            print("Convex hull failed (likely due to mock zero data collapsing all points together).")
            
        # Add the points explicitly so they are visible inside the hull
        scene.add_geometry(point_cloud)
    else:
        # Default Point Cloud
        points = trimesh.points.PointCloud(vertices)
        scene.add_geometry(points)
        
    # Open the 3D interactive viewer
    scene.show(caption="HaMeR 3D Hand Mesh Viewer")

def load_mano_faces(path="mano_v1_2/models/MANO_RIGHT.pkl"):
    """
    Placeholder to load MANO faces if user has downloaded SMPL/MANO models.
    """
    if os.path.exists(path):
        try:
             # In a real environment with SMPL
             import pickle
             with open(path, 'rb') as f:
                data = pickle.load(f, encoding='latin1')
             return data['f']
        except Exception as e:
             print(f"Failed to load MANO faces: {e}")
    return None

def main():
    parser = argparse.ArgumentParser(description="Visualize output files from Stage 1.1")
    parser.add_argument('--file', type=str, required=True, help="Path to the HDF5 file (e.g. output/0_stage1.hdf5)")
    parser.add_argument('--frame', type=int, default=0, help="Frame index to visualize (default: 0)")
    parser.add_argument('--style', type=str, choices=['points', 'surface'], default='points', help="Render as 'points' or attempting solid 'surface'.")
    parser.add_argument('--mano_path', type=str, default=None, help="Path to MANO pickle for valid topological faces")
    
    args = parser.parse_args()
    
    if not os.path.exists(args.file):
        print(f"Error: Could not find {args.file}")
        return

    print(f"Reading HDF5: {args.file} (Frame: {args.frame})")
    
    try:
        with h5py.File(args.file, 'r') as hf:
            if 'hamer_mesh' in hf.keys() and 'moge_depth_map' in hf.keys():
                hamer_meshes = hf['hamer_mesh'][:]
                moge_depths = hf['moge_depth_map'][:]
                
                if args.frame >= len(hamer_meshes):
                    print(f"Error: Frame index {args.frame} is out of bounds (Total Frames: {len(hamer_meshes)}).")
                    return
                
                v_mesh = hamer_meshes[args.frame]
                v_depth = moge_depths[args.frame]
                
                # Alert if data is zero/mocked
                if np.all(v_mesh == 0) and np.all(v_depth == 0):
                   print("\n=======================================================")
                   print("WARNING: Data matrices are completely populated by ZEROS.")
                   print("This confirms you synced the HDF5 generated by the scaffold code.")
                   print("Visualization of the mesh will appear as a single dot at (0,0,0).")
                   print("=======================================================\n")
                   
                # Display Depth
                print("-> Opening Depth Map Viewer. Please close the Matplotlib image to proceed to the 3D Mesh Viewer.")
                visualize_depth(v_depth, args.frame)
                
                # Setup faces if requested
                faces = None
                if args.style == 'surface' and args.mano_path:
                    faces = load_mano_faces(args.mano_path)
                
                # Display Mesh
                print(f"-> Opening 3D Hand Viewer ({args.style})")
                visualize_mesh(v_mesh, use_surface=(args.style == 'surface'), faces=faces)
            else:
                 print("Error: HDF5 file is missing expected keys ('hamer_mesh', 'moge_depth_map')")
                 print(f"Keys found: {list(hf.keys())}")
    except Exception as e:
        print(f"Failed to read or visualize data: {e}")

if __name__ == "__main__":
    main()
